trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'
  displayName: 'Set up Ruby'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'Install Dependencies'

- script: bundle exec rake
  displayName: 'Run Rake Tasks'

# Add steps to package the application if needed (e.g., create a tarball)
- script: |
    tar -czf app.tar.gz .
  displayName: 'Package Application'

# Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: '<your-azure-subscription>' # Replace with your Azure subscription service connection
    appName: '<your-app-name>' # Replace with your Azure App Service name
    package: '$(Build.ArtifactStagingDirectory)/app.tar.gz' # Path to your package file
  displayName: 'Deploy to Azure App Service'

# Publish build artifacts (optional)
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
  displayName: 'Publish Build Artifacts'
