# db/seeds.rb

# Create cities
cities = [
  { "name": "Mumbai", "location": "Maharashtra" },
  { "name": "Delhi", "location": "Delhi" },
  { "name": "Kolkata", "location": "West Bengal" },
  { "name": "Chennai", "location": "Tamil Nadu" },
  { "name": "Bengaluru", "location": "Karnataka" },
  { "name": "Bangalore", "location": "Karnataka" },
  { "name": "Agartala", "location": "Tripura" },
  { "name": "Aizawl", "location": "Mizoram" },
  { "name": "Amaravati", "location": "Andhra Pradesh" },
  { "name": "Bhopal", "location": "Madhya Pradesh" },
  { "name": "Bhubaneswar", "location": "Odisha" },
  { "name": "Chandigarh", "location": "Chandigarh" },
  { "name": "Dehradun", "location": "Uttarakhand" },
  { "name": "Dispur", "location": "Assam" },
  { "name": "Gandhinagar", "location": "Gujarat" },
  { "name": "Gangtok", "location": "Sikkim" },
  { "name": "Hyderabad", "location": "Telangana" },
  { "name": "Imphal", "location": "Manipur" },
  { "name": "Itanagar", "location": "Arunachal Pradesh" },
  { "name": "Jaipur", "location": "Rajasthan" },
  { "name": "Jammu", "location": "Jammu and Kashmir" },
  { "name": "Kohima", "location": "Nagaland" },
  { "name": "Lucknow", "location": "Uttar Pradesh" },
  { "name": "Patna", "location": "Bihar" },
  { "name": "Raipur", "location": "Chhattisgarh" },
  { "name": "Ranchi", "location": "Jharkhand" },
  { "name": "Shillong", "location": "Meghalaya" },
  { "name": "Shimla", "location": "Himachal Pradesh" },
  { "name": "Srinagar", "location": "Jammu and Kashmir" },
  { "name": "Thiruvananthapuram", "location": "Kerala" }
]

    # Add more cities as needed


cities.each do |city_data|
  City.find_or_create_by(name: city_data[:name]) do |city|
    city.update(city_data)
  end
end

# Create routes
routes = [
  { "start_city_name": "Mumbai", "end_city_name": "Agartala", "duration": 144 },
  { "start_city_name": "Mumbai", "end_city_name": "Aizawl", "duration": 140 },
  { "start_city_name": "Agartala", "end_city_name": "Aizawl", "duration": 40 },
  { "start_city_name": "Agartala", "end_city_name": "Amaravati", "duration": 12440 },
  { "start_city_name": "Aizawl", "end_city_name": "Amaravati", "duration": 400 },
  { "start_city_name": "Mumbai", "end_city_name": "Bengaluru", "duration": 360 },
  { "start_city_name": "Amaravati", "end_city_name": "Agartala", "duration": 720 },
  { "start_city_name": "Bengaluru", "end_city_name": "Mumbai", "duration": 280 },
  { "start_city_name": "Agartala", "end_city_name": "Bengaluru", "duration": 820 },
  { "start_city_name": "Aizawl", "end_city_name": "Bengaluru", "duration": 660 },
  { "start_city_name": "Bengaluru", "end_city_name": "Amaravati", "duration": 220 },
  { "start_city_name": "Mumbai", "end_city_name": "Amaravati", "duration": 520 },
  { "start_city_name": "Amaravati", "end_city_name": "Agartala", "duration": 780 },
  { "start_city_name": "Bengaluru", "end_city_name": "Aizawl", "duration": 1400 },
  { "start_city_name": "Agartala", "end_city_name": "Aizawl", "duration": 200 },
  { "start_city_name": "Aizawl", "end_city_name": "Mumbai", "duration": 180 },
  { "start_city_name": "Mumbai", "end_city_name": "Bengaluru", "duration": 240 },
  { "start_city_name": "Amaravati", "end_city_name": "Bengaluru", "duration": 420 },
  { "start_city_name": "Bengaluru", "end_city_name": "Aizawl", "duration": 300 },
  { "start_city_name": "Agartala", "end_city_name": "Amaravati", "duration": 960 },
  { "start_city_name": "Amaravati", "end_city_name": "Agartala", "duration": 540 },
  { "start_city_name": "Aizawl", "end_city_name": "Mumbai", "duration": 600 },
  { "start_city_name": "Bengaluru", "end_city_name": "Amaravati", "duration": 480 },
  { "start_city_name": "Mumbai", "end_city_name": "Aizawl", "duration": 320 },
  { "start_city_name": "Amaravati", "end_city_name": "Agartala", "duration": 1120 },
  { "start_city_name": "Bengaluru", "end_city_name": "Aizawl", "duration": 140 },
  { "start_city_name": "Agartala", "end_city_name": "Amaravati", "duration": 480 },
  { "start_city_name": "Amaravati", "end_city_name": "Agartala", "duration": 440 },
  { "start_city_name": "Aizawl", "end_city_name": "Mumbai", "duration": 540 },
  { "start_city_name": "Bengaluru", "end_city_name": "Amaravati", "duration": 420 },
  { "start_city_name": "Mumbai", "end_city_name": "Aizawl", "duration": 360 },
  { "start_city_name": "Agartala", "end_city_name": "Amaravati", "duration": 380 },
  { "start_city_name": "Amaravati", "end_city_name": "Agartala", "duration": 280 },
  { "start_city_name": "Aizawl", "end_city_name": "Mumbai", "duration": 460 },
  { "start_city_name": "Bengaluru", "end_city_name": "Amaravati", "duration": 260 },
  { "start_city_name": "Mumbai", "end_city_name": "Aizawl", "duration": 500 },
  { "start_city_name": "Agartala", "end_city_name": "Amaravati", "duration": 720 },
  { "start_city_name": "Amaravati", "end_city_name": "Agartala", "duration": 940 },
  { "start_city_name": "Aizawl", "end_city_name": "Mumbai", "duration": 240 },
  { "start_city_name": "Bengaluru", "end_city_name": "Amaravati", "duration": 680 },
  { "start_city_name": "Mumbai", "end_city_name": "Aizawl", "duration": 500 },
  { "start_city_name": "Agartala", "end_city_name": "Amaravati", "duration": 360 },
  { "start_city_name": "Amaravati", "end_city_name": "Agartala", "duration": 440 },
  { "start_city_name": "Aizawl", "end_city_name": "Mumbai", "duration": 380 },
  { "start_city_name": "Bengaluru", "end_city_name": "Amaravati", "duration": 240 },
  { "start_city_name": "Mumbai", "end_city_name": "Agartala", "duration": 144 },
  { "start_city_name": "Mumbai", "end_city_name": "Aizawl", "duration": 140 },
  { "start_city_name": "Mumbai", "end_city_name": "Amaravati", "duration": 160 },
  { "start_city_name": "Mumbai", "end_city_name": "Bangalore", "duration": 240 },
  { "start_city_name": "Mumbai", "end_city_name": "Bhopal", "duration": 180 },
  { "start_city_name": "Mumbai", "end_city_name": "Bhubaneswar", "duration": 220 },
  { "start_city_name": "Mumbai", "end_city_name": "Chandigarh", "duration": 280 },
  { "start_city_name": "Mumbai", "end_city_name": "Chennai", "duration": 260 },
  { "start_city_name": "Mumbai", "end_city_name": "Dehradun", "duration": 300 },
  { "start_city_name": "Mumbai", "end_city_name": "Dispur", "duration": 320 },
  { "start_city_name": "Mumbai", "end_city_name": "Gandhinagar", "duration": 160 },
  { "start_city_name": "Mumbai", "end_city_name": "Gangtok", "duration": 360 },
  { "start_city_name": "Mumbai", "end_city_name": "Hyderabad", "duration": 200 },
  { "start_city_name": "Mumbai", "end_city_name": "Imphal", "duration": 340 },
  { "start_city_name": "Mumbai", "end_city_name": "Itanagar", "duration": 380 },
  { "start_city_name": "Mumbai", "end_city_name": "Jaipur", "duration": 180 },
  { "start_city_name": "Mumbai", "end_city_name": "Jammu", "duration": 300 },
  { "start_city_name": "Mumbai", "end_city_name": "Kohima", "duration": 400 },
  { "start_city_name": "Mumbai", "end_city_name": "Kolkata", "duration": 220 },
  { "start_city_name": "Mumbai", "end_city_name": "Lucknow", "duration": 260 },
  { "start_city_name": "Mumbai", "end_city_name": "Patna", "duration": 280 },
  { "start_city_name": "Mumbai", "end_city_name": "Raipur", "duration": 200 },
  { "start_city_name": "Mumbai", "end_city_name": "Ranchi", "duration": 280 },
  { "start_city_name": "Mumbai", "end_city_name": "Shillong", "duration": 340 },
  { "start_city_name": "Mumbai", "end_city_name": "Shimla", "duration": 300 },
  { "start_city_name": "Mumbai", "end_city_name": "Srinagar", "duration": 380 },
  { "start_city_name": "Mumbai", "end_city_name": "Thiruvananthapuram", "duration": 360 },
  { "start_city_name": "Mumbai", "end_city_name": "Agartala", "duration": 144 },
  { "start_city_name": "Mumbai", "end_city_name": "Aizawl", "duration": 140 },
  { "start_city_name": "Mumbai", "end_city_name": "Amaravati", "duration": 160 },
  { "start_city_name": "Mumbai", "end_city_name": "Bangalore", "duration": 240 },
  { "start_city_name": "Mumbai", "end_city_name": "Bhopal", "duration": 180 },
  { "start_city_name": "Mumbai", "end_city_name": "Bhubaneswar", "duration": 220 },
  { "start_city_name": "Mumbai", "end_city_name": "Chandigarh", "duration": 280 },
  { "start_city_name": "Mumbai", "end_city_name": "Chennai", "duration": 260 },
  { "start_city_name": "Mumbai", "end_city_name": "Dehradun", "duration": 300 },
  { "start_city_name": "Mumbai", "end_city_name": "Dispur", "duration": 320 },
  { "start_city_name": "Mumbai", "end_city_name": "Gandhinagar", "duration": 160 },
  { "start_city_name": "Mumbai", "end_city_name": "Gangtok", "duration": 360 },
  { "start_city_name": "Mumbai", "end_city_name": "Hyderabad", "duration": 200 },
  { "start_city_name": "Mumbai", "end_city_name": "Imphal", "duration": 340 },
  { "start_city_name": "Mumbai", "end_city_name": "Itanagar", "duration": 380 },
  { "start_city_name": "Mumbai", "end_city_name": "Jaipur", "duration": 180 },
  { "start_city_name": "Mumbai", "end_city_name": "Jammu", "duration": 300 },
  { "start_city_name": "Mumbai", "end_city_name": "Kohima", "duration": 400 },
  { "start_city_name": "Mumbai", "end_city_name": "Kolkata", "duration": 220 },
  { "start_city_name": "Mumbai", "end_city_name": "Lucknow", "duration": 260 },
  { "start_city_name": "Mumbai", "end_city_name": "Patna", "duration": 280 },
  { "start_city_name": "Mumbai", "end_city_name": "Raipur", "duration": 200 },
  { "start_city_name": "Mumbai", "end_city_name": "Ranchi", "duration": 280 },
  { "start_city_name": "Mumbai", "end_city_name": "Shillong", "duration": 340 },
  { "start_city_name": "Mumbai", "end_city_name": "Shimla", "duration": 300 },
  { "start_city_name": "Mumbai", "end_city_name": "Srinagar", "duration": 380 },
  { "start_city_name": "Mumbai", "end_city_name": "Thiruvananthapuram", "duration": 360 },
  { "start_city_name": "Delhi", "end_city_name": "Agartala", "duration": 144 },
  { "start_city_name": "Delhi", "end_city_name": "Aizawl", "duration": 140 },
  { "start_city_name": "Delhi", "end_city_name": "Amaravati", "duration": 160 },
  { "start_city_name": "Delhi", "end_city_name": "Bangalore", "duration": 240 },
  { "start_city_name": "Delhi", "end_city_name": "Bhopal", "duration": 180 },
  { "start_city_name": "Delhi", "end_city_name": "Bhubaneswar", "duration": 220 },
  { "start_city_name": "Delhi", "end_city_name": "Chandigarh", "duration": 280 },
  { "start_city_name": "Delhi", "end_city_name": "Chennai", "duration": 260 },
  { "start_city_name": "Delhi", "end_city_name": "Dehradun", "duration": 300 },
  { "start_city_name": "Delhi", "end_city_name": "Dispur", "duration": 320 },
  { "start_city_name": "Delhi", "end_city_name": "Gandhinagar", "duration": 160 },
  { "start_city_name": "Delhi", "end_city_name": "Gangtok", "duration": 360 },
  { "start_city_name": "Delhi", "end_city_name": "Hyderabad", "duration": 200 },
  { "start_city_name": "Delhi", "end_city_name": "Imphal", "duration": 340 },
  { "start_city_name": "Delhi", "end_city_name": "Itanagar", "duration": 380 },
  { "start_city_name": "Delhi", "end_city_name": "Jaipur", "duration": 180 },
  { "start_city_name": "Delhi", "end_city_name": "Jammu", "duration": 300 },
  { "start_city_name": "Delhi", "end_city_name": "Kohima", "duration": 400 },
  { "start_city_name": "Delhi", "end_city_name": "Kolkata", "duration": 220 },
  { "start_city_name": "Delhi", "end_city_name": "Lucknow", "duration": 260 },
  { "start_city_name": "Delhi", "end_city_name": "Patna", "duration": 280 },
  { "start_city_name": "Delhi", "end_city_name": "Raipur", "duration": 200 },
  { "start_city_name": "Delhi", "end_city_name": "Ranchi", "duration": 280 },
  { "start_city_name": "Delhi", "end_city_name": "Shillong", "duration": 340 },
  { "start_city_name": "Delhi", "end_city_name": "Shimla", "duration": 300 },
  { "start_city_name": "Delhi", "end_city_name": "Srinagar", "duration": 380 },
  { "start_city_name": "Delhi", "end_city_name": "Thiruvananthapuram", "duration": 360 },
  { "start_city_name": "Kolkata", "end_city_name": "Agartala", "duration": 144 },
  { "start_city_name": "Kolkata", "end_city_name": "Aizawl", "duration": 140 },
  { "start_city_name": "Kolkata", "end_city_name": "Amaravati", "duration": 160 },
  { "start_city_name": "Kolkata", "end_city_name": "Bangalore", "duration": 240 },
  { "start_city_name": "Kolkata", "end_city_name": "Bhopal", "duration": 180 },
  { "start_city_name": "Kolkata", "end_city_name": "Bhubaneswar", "duration": 220 },
  { "start_city_name": "Kolkata", "end_city_name": "Chandigarh", "duration": 280 },
  { "start_city_name": "Kolkata", "end_city_name": "Chennai", "duration": 260 },
  { "start_city_name": "Kolkata", "end_city_name": "Dehradun", "duration": 300 },
  { "start_city_name": "Kolkata", "end_city_name": "Dispur", "duration": 320 },
  { "start_city_name": "Kolkata", "end_city_name": "Gandhinagar", "duration": 160 },
  { "start_city_name": "Kolkata", "end_city_name": "Gangtok", "duration": 360 },
  { "start_city_name": "Kolkata", "end_city_name": "Hyderabad", "duration": 200 },
  { "start_city_name": "Kolkata", "end_city_name": "Imphal", "duration": 340 },
  { "start_city_name": "Kolkata", "end_city_name": "Itanagar", "duration": 380 },
  { "start_city_name": "Kolkata", "end_city_name": "Jaipur", "duration": 180 },
  { "start_city_name": "Kolkata", "end_city_name": "Jammu", "duration": 300 },
]


routes.each do |route_data|
  start_city = City.find_by(name: route_data[:start_city_name])
  end_city = City.find_by(name: route_data[:end_city_name])

  if start_city.nil?
    puts "Start city '#{route_data[:start_city_name]}' not found in the database."
    next
  end

  if end_city.nil?
    puts "End city '#{route_data[:end_city_name]}' not found in the database."
    next
  end

  Route.create!(start_city_id: start_city.id, end_city_id: end_city.id, duration: route_data[:duration])
end
